// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ1xw_wWYZvaDVlwsmq1jqNQQBrLmAHZQ',
    appId: '1:436403604797:web:43ba189163094f5e9b0954',
    messagingSenderId: '436403604797',
    projectId: 'crudflutter-3b0fa',
    authDomain: 'crudflutter-3b0fa.firebaseapp.com',
    storageBucket: 'crudflutter-3b0fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAALBXAC7bD7yAp4C5T-MpC8wTjT-I6xog',
    appId: '1:436403604797:android:f254ad0836d1c5ad9b0954',
    messagingSenderId: '436403604797',
    projectId: 'crudflutter-3b0fa',
    storageBucket: 'crudflutter-3b0fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Hg197HyUFzsWA3IPlLmxj1IBCGYURnc',
    appId: '1:436403604797:ios:f45219abccd978d29b0954',
    messagingSenderId: '436403604797',
    projectId: 'crudflutter-3b0fa',
    storageBucket: 'crudflutter-3b0fa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Hg197HyUFzsWA3IPlLmxj1IBCGYURnc',
    appId: '1:436403604797:ios:9b538108329394239b0954',
    messagingSenderId: '436403604797',
    projectId: 'crudflutter-3b0fa',
    storageBucket: 'crudflutter-3b0fa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
